spring:
  application:
    name: zuul-proxy

server:
  port: 8090

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300